version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: user-management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - user-management-network

  app:
    build: .
    container_name: user-management-api
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - user-management-network

volumes:
  mysql_data:

networks:
  user-management-network:
    driver: bridge